# Generated by Django 3.2.5 on 2021-07-13 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_info_file_info_link'),
        ('project', '0006_alter_project_education_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('from_user_id', models.ForeignKey(db_column='from_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='scrap_from_user_id', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('to_user_id', models.ForeignKey(db_column='to_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrap_to_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('com_id', models.ForeignKey(db_column='com_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='community.com')),
                ('from_user_id', models.ForeignKey(db_column='from_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='like_from_user_id', to=settings.AUTH_USER_MODEL)),
                ('info_id', models.ForeignKey(db_column='info_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='community.info')),
                ('project_id', models.ForeignKey(db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('to_user_id', models.ForeignKey(db_column='to_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='like_to_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
