# Generated by Django 3.2.4 on 2021-06-30 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('now', models.IntegerField()),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.IntegerField()),
                ('isEnd', models.IntegerField()),
                ('type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('field2', models.CharField(max_length=20)),
                ('mem_total', models.IntegerField()),
                ('mem_now', models.IntegerField()),
                ('mem_duty', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.IntegerField()),
                ('school', models.CharField(max_length=45, null=True)),
                ('content', models.TextField()),
                ('isLink', models.IntegerField()),
                ('isFile', models.IntegerField()),
                ('view_cnt', models.IntegerField()),
                ('education_id', models.ForeignKey(db_column='education_id', on_delete=django.db.models.deletion.CASCADE, to='home.education')),
                ('field1_id', models.ForeignKey(db_column='field1_id', on_delete=django.db.models.deletion.CASCADE, to='home.field1')),
                ('region1_id', models.ForeignKey(db_column='region1_id', on_delete=django.db.models.deletion.CASCADE, to='home.region1')),
                ('region2_id', models.ForeignKey(db_column='region2_id', on_delete=django.db.models.deletion.CASCADE, to='home.region2')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=45)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=45)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_id', models.ForeignKey(db_column='duty_id', on_delete=django.db.models.deletion.CASCADE, to='project.duty')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='duty',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
