# Generated by Django 3.2.4 on 2021-07-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('project', '0002_alter_project_view_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='education_id',
            field=models.ForeignKey(db_column='education_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.education'),
        ),
        migrations.AlterField(
            model_name='project',
            name='school',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
