# Generated by Django 3.2.5 on 2021-07-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('project', '0005_alter_project_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='education_id',
            field=models.ForeignKey(db_column='education_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.education'),
        ),
    ]
