# Generated by Django 3.2.5 on 2021-07-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_apply_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply_form',
        ),
    ]
