# Generated by Django 3.2.5 on 2021-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='register_state',
            field=models.IntegerField(default=0),
        ),
    ]
