# Generated by Django 3.2.5 on 2021-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_question_choice_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isRequired',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
