# Generated by Django 3.2.5 on 2021-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_question_isrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
