# Generated by Django 3.2.5 on 2021-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='term',
            field=models.IntegerField(default=1),
        ),
    ]
