# Generated by Django 3.2.4 on 2021-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_mbti_mbti_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
