# Generated by Django 3.2.4 on 2021-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_mbti_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
