# Generated by Django 3.2.5 on 2021-07-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
