# Generated by Django 3.2.5 on 2021-07-16 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
