# Generated by Django 3.2.5 on 2021-07-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_type',
            field=models.IntegerField(),
        ),
    ]
