# Generated by Django 3.2.5 on 2021-07-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_alter_project_education_id'),
        ('account', '0009_message'),
        ('home', '0002_like_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=100)),
                ('message_id', models.ForeignKey(db_column='message_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.message')),
                ('project_id', models.ForeignKey(db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('rec_user_id', models.ForeignKey(db_column='rec_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_to_user_id', to=settings.AUTH_USER_MODEL)),
                ('to_user_id', models.ForeignKey(db_column='to_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_to_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
