# Generated by Django 3.2.5 on 2021-07-19 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_noti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='to_user_id',
            field=models.ForeignKey(db_column='to_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
