# Generated by Django 3.2.5 on 2021-07-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210716_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
