# Generated by Django 3.2.5 on 2021-08-02 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_review_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
