# Generated by Django 3.2.5 on 2021-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_message_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
