# Generated by Django 3.2.5 on 2021-08-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_message_payment_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
