# Generated by Django 3.2.4 on 2021-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
