# Generated by Django 3.2.5 on 2021-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210716_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='now',
            field=models.IntegerField(default=0),
        ),
    ]
