# Generated by Django 3.2.5 on 2021-07-22 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_duty_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='register',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
