# Generated by Django 3.2.5 on 2021-07-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
