# Generated by Django 3.2.5 on 2021-07-23 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0018_delete_apply_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('q10_id', models.ForeignKey(db_column='q10_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q10_id', to='project.question')),
                ('q1_id', models.ForeignKey(db_column='q1_id', on_delete=django.db.models.deletion.CASCADE, related_name='q1_id', to='project.question')),
                ('q2_id', models.ForeignKey(db_column='q2_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q2_id', to='project.question')),
                ('q3_id', models.ForeignKey(db_column='q3_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q3_id', to='project.question')),
                ('q4_id', models.ForeignKey(db_column='q4_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q4_id', to='project.question')),
                ('q5_id', models.ForeignKey(db_column='q5_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q5_id', to='project.question')),
                ('q6_id', models.ForeignKey(db_column='q6_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q6_id', to='project.question')),
                ('q7_id', models.ForeignKey(db_column='q7_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q7_id', to='project.question')),
                ('q8_id', models.ForeignKey(db_column='q8_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q8_id', to='project.question')),
                ('q9_id', models.ForeignKey(db_column='q9_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q9_id', to='project.question')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
