# Generated by Django 3.2.5 on 2021-07-23 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0020_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.IntegerField()),
                ('a10_id', models.ForeignKey(db_column='a10_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a10_id', to='project.answer')),
                ('a1_id', models.ForeignKey(db_column='a1_id', on_delete=django.db.models.deletion.CASCADE, related_name='a1_id', to='project.answer')),
                ('a2_id', models.ForeignKey(db_column='a2_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a2_id', to='project.answer')),
                ('a3_id', models.ForeignKey(db_column='a3_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a3_id', to='project.answer')),
                ('a4_id', models.ForeignKey(db_column='a4_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a4_id', to='project.answer')),
                ('a5_id', models.ForeignKey(db_column='a5_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a5_id', to='project.answer')),
                ('a6_id', models.ForeignKey(db_column='a6_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a6_id', to='project.answer')),
                ('a7_id', models.ForeignKey(db_column='a7_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a7_id', to='project.answer')),
                ('a8_id', models.ForeignKey(db_column='a8_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a8_id', to='project.answer')),
                ('a9_id', models.ForeignKey(db_column='a9_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a9_id', to='project.answer')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
