# Generated by Django 3.2.5 on 2021-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_member_register_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
