# Generated by Django 3.2.5 on 2021-07-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=45)),
                ('info_id', models.ForeignKey(db_column='info_id', on_delete=django.db.models.deletion.CASCADE, to='community.info')),
            ],
        ),
        migrations.CreateModel(
            name='Info_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('info_id', models.ForeignKey(db_column='info_id', on_delete=django.db.models.deletion.CASCADE, to='community.info')),
            ],
        ),
    ]
