# Generated by Django 3.2.5 on 2021-07-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_info_file_info_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com',
            name='title',
        ),
    ]
