# Generated by Django 3.2.5 on 2021-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_com_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
