# Generated by Django 3.2.5 on 2021-07-31 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_info_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='info',
            name='write_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
