# Generated by Django 3.2.5 on 2021-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20210731_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='isFile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='isLink',
            field=models.IntegerField(default=0),
        ),
    ]
