# Generated by Django 3.2.5 on 2021-08-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20210731_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
